import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import main from '../styles/Home.module.css'
import { useRouter } from "next/router";

import en from '../locales/en';
import ar from '../locales/ar';

import banner_img from '../public/images/banner_logo.png'
import overview from '../public/images/overview.svg'

export default function Home() {
  var router = useRouter();
  let t = router.locale === 'en' ? en : ar;
  return (
    <>
      <Head>
        <title>{t.title.home}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* cover */}
      <main className={`${main.banner}`}>
        <div className='row'>
          <div className={main.img}>
            <div className={main.cover}>
              <div className='container' style={{ 'height': 'inherit' }}>
                <div className={`row`} style={{ 'height': '66%' }}>
                  <section>
                    <div className={`row ${main.custReverse}`}>
                      <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
                        <h1>Our main principle prevailing is</h1>
                        <p>Reaching clients to the goal that they aspire to have a trained and specialized staff that understands the needs of each individual client</p>
                        <Link href="/">
                          <a>
                            <button className={`btn btn-primary`}>Contact us</button>
                            <button className={`btn btn-primary ${main.btn_srvs}`}>Services</button>
                          </a>
                        </Link>
                      </div>
                      <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`}>
                        <img src={banner_img.src} style={{ "max-width": "100%", "margin-bottom": "20px" }} />
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Overview section */}
      <div className={`row ${main.overview}`}>
        <div className='container'>
          <div className={`row ${main.column}`}>
            <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
              <h4>An overview of Ibrahim Al-Sulami's office</h4>
              <p>Ibrahim Al Sulami Office is accountants and certified auditors one of the best auditing and accounting companies in the Kingdom of Saudi Arabia, where we provide financial, accounting and tax consulting services, auditing and auditing, internal audit of companies and bookkeeping accounting. We aim to enhance customer added value by providing distinguished financial, administrative and technical services in the aforementioned fields of work. Accounting is the basis for any successful business</p>
              <button className={`btn btn-primary ${main.btn_srvs}`}>
                <a href='/'>Read more</a>
              </button>
            </div>
            <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`}>
              <img src={overview.src} style={{ "max-width": "100%", "margin-bottom": "20px" }} />
            </div>
          </div>
        </div>
      </div>

      {/* Our Value  */}
      <div className={`row ${main.our_value}`}>
        <div className='container'>
          <div className='row'>
            <div className='row'>
              <div className='col-xs-12 col-sm-12 col-md-12 col-lg-12'>
                <h4>Our Value</h4>
                <p>We work for you towards continuous progress and development. We firmly believe in the pursuit of excellence. We join a wonderful team of distinguished accountants and auditors, specialists and qualified to provide excellent financial, administrative and tax services. We are experienced in eliminating the storms that threaten them and identifying weaknesses that must be focused on and not overlooked. Our motto is confidence, excellence, challenge.</p>
              </div>
            </div>
            <div className='row'>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Empowerment</h6>
                <p>We give the authority to our employees so that they can provide all customer services without going back to higher levels.</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Respect the time</h6>
                <p>We provide clients with a schedule that we stick to, and that prompts us to be more effective and focused on achieving the goal.</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Honesty</h6>
                <p>We adhere to the privacy policy of every client and take a sophisticated ethical course on the individual and team level.</p>
              </div>

              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Employee loyalty</h6>
                <p className={`${main.p}`}>Encouraging and rewarding creative and distinguished people and putting the right person in the right place.</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Team work</h6>
                <p className={`${main.p}`}>Our motto The word "we" is more important than the word "I" and we attribute our success to the entire team and not to a specific employee.</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>Perseverance</h6>
                <p className={`${main.p}`}>Success does not come by chance, but rather is the result of achieving all the goals and aspirations of customers.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Our Services */}
      <div className={`row ${main.our_services}`}>
        <div className='container'>
            <h4>Our Services</h4>
          <div className='row'>
          <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-file-invoice-dollar"></i>
                </p>
                <h6>Value Added Services</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-search-dollar"></i>
                </p>
                <h6>Internal audit</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-coins"></i>
                </p>
                <h6>Preparing financial statements</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-comment-dollar"></i>
                </p>
                <h6>Zakat and income reports</h6>
              </div>
            </div>

            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-receipt"></i>
                </p>
                <h6>Accounting bookkeeping</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-university"></i>
                </p>
                <h6>Financial consulting</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-desktop"></i>
                </p>
                <h6>Accounting software</h6>
              </div>
            </div>
            <div className='col-xs-6 col-sm-6 col-md-3 col-lg-3' style={{'padding': '5px'}}>
              <div className={`card ${main.card}`}>
                <p>
                  <i class="fas fa-hand-holding-usd"></i>
                </p>
                <h6>Tax and Zakat Consulting</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
