import Head from 'next/head'
import Slider from "react-slick";
import Link from 'next/link'
import main from '../styles/Home.module.css'
import { useRouter } from "next/router";
import Services from '../components/services'

import en from '../locales/en';
import ar from '../locales/ar';

import banner_img from '../public/images/banner_logo.png'
import overview from '../public/images/overview.svg'

// parteners images
import dell from '../public/images/parteners/dell.png'
import aldawaa from '../public/images/parteners/Aldawaa-logo.png'
import aldawaa_pharmacy from '../public/images/parteners/Aldawaa-pharmacy.png'
import asalet from '../public/images/parteners/Asalet-Elarab.png'
import atlas from '../public/images/parteners/Atlas-elevators.png'
import browneagle from '../public/images/parteners/browneagle.png'
import fullscreen from '../public/images/parteners/full-screen.png'
import moj from '../public/images/parteners/moj-logo.png'
import secureEyes from '../public/images/parteners/Secureeyes.png'
import servicesSolutions from '../public/images/parteners/Services-Solutions.png'
import sharek from '../public/images/parteners/Sharek.png'
import spsc from '../public/images/parteners/SPSC.png'

// Teamwork
import ibrahim_alsulmi from '../public/images/team/ibrahim_alsulmi.jpg'
import khaled from '../public/images/team/khaled.jpeg'
import otba_bakr from '../public/images/team/otba-bakr.jpg'
import yosef_alsulmi from '../public/images/team/yosef_alsulmi.jpg'

export default function Home() {
  var router = useRouter();
  let t = router.locale === 'en' ? en : ar;

  const settings = {
    centerMode: true,
    centerPadding: '60px',
    slidesToShow: 3,
    responsive: [
      {
        breakpoint: 999,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '30px',
          slidesToShow: 2
        }
      },
      {  
        breakpoint: 767,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '20px',
          slidesToShow: 1
        }
      },
      {
        breakpoint: 480,
        settings: {
          arrows: false,
          centerMode: true,
          centerPadding: '20px',
          slidesToShow: 1
        }
      }
    ]
  };
  return (

    <>
      <Head>
        <title>{t.title.home}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* cover */}
   
      <main className={`${main.banner} bannerAr`}>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="carousel-item active">
            {/* <img class="d-block w-100" src="..." alt="First slide" /> */}
            <div className={main.img}>
            <div className={main.cover}>
              <div className='container' style={{ 'height': 'inherit' }}>
                <div className={`row`} style={{ 'height': '66%' }}>
                  <section>
                    <div className={`row ${main.custReverse}`}>
                      <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
                        <h1>{t.banner.title}</h1>
                        <p>{t.banner.desc}</p>
                        <Link href="/">
                          <a>
                            <button className={`btn btn-primary`}>{t.banner.contact_btn}</button>
                            <button className={`btn btn-primary ${main.btn_srvs}`}>{t.banner.servs_btn}</button>
                          </a>
                        </Link>
                      </div>
                      <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`} align='center'>
                        <img src={banner_img.src} style={{ "max-width": "100%", "margin-bottom": "20px", "width": "120px" }} />
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </div>
          </div>
          <div class="carousel-item">
            {/* <img class="d-block w-100" src="..." alt="Second slide" /> */}
            <div className={main.img}>
            <div className={main.cover}>
              <div className='container' style={{ 'height': 'inherit' }}>
                <div className={`row`} style={{ 'height': '66%' }}>
                  <section>
                    <div className={`row ${main.custReverse}`}>
                      <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
                        <h1>{t.banner.title} 2</h1>
                        <p>{t.banner.desc}</p>
                        <Link href="/">
                          <a>
                            <button className={`btn btn-primary`}>{t.banner.contact_btn}</button>
                            <button className={`btn btn-primary ${main.btn_srvs}`}>{t.banner.servs_btn}</button>
                          </a>
                        </Link>
                      </div>
                      <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`} align='center'>
                        <img src={banner_img.src} style={{ "max-width": "100%", "margin-bottom": "20px", "width": "120px" }} />
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </div>
          </div>
          <div class="carousel-item">
            {/* <img class="d-block w-100" src="..." alt="Third slide" /> */}
            <div className={main.img}>
            <div className={main.cover}>
              <div className='container' style={{ 'height': 'inherit' }}>
                <div className={`row`} style={{ 'height': '66%' }}>
                  <section>
                    <div className={`row ${main.custReverse}`}>
                      <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
                        <h1>{t.banner.title} 3</h1>
                        <p>{t.banner.desc}</p>
                        <Link href="/">
                          <a>
                            <button className={`btn btn-primary`}>{t.banner.contact_btn}</button>
                            <button className={`btn btn-primary ${main.btn_srvs}`}>{t.banner.servs_btn}</button>
                          </a>
                        </Link>
                      </div>
                      <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`} align='center'>
                        <img src={banner_img.src} style={{ "max-width": "100%", "margin-bottom": "20px", "width": "120px" }} />
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      </main>

      {/* Overview section */}
      <section id='about_us'>
      <div className={`row ${main.overview}`}>
        <div className='container'>
          <div className={`row ${main.column}`}>
            <div className={`col-xs-12 col-sm-12 col-md-8 col-lg-8`}>
              <h4>{t.overview.title}</h4>
              <p>{t.overview.desc}</p>
              {/* <button className={`btn btn-primary ${main.btn_srvs}`}>
                <a href='/'>Read more</a>
              </button> */}
            </div>
            <div className={`col-xs-12 col-sm-12 col-md-4 col-lg-4`}>
              <img src={overview.src} style={{ "max-width": "100%", "margin-bottom": "20px" }} />
            </div>
          </div>
        </div>
      </div>

      </section>
      {/* Our Value  */}
      <div className={`row ${main.our_value}`} id='our_value'>
        <div className='container'>
          <div className='row'>
            <div className='row'>
              <div className='col-xs-12 col-sm-12 col-md-12 col-lg-12'>
                <h4>{t.our_value.title}</h4>
                <p style={{ "margin-bottom": "2rem" }}>{t.our_value.desc}</p>
              </div>
            </div>
            <div className='row'>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.empowerment.title}</h6>
                <p pAr>{t.our_value.empowerment.desc}</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.respectTheTime.title}</h6>
                <p pAr>{t.our_value.respectTheTime.desc}</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.honesty.title}</h6>
                <p pAr>{t.our_value.honesty.desc}</p>
              </div>

              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.employeeLoyalty.title}</h6>
                <p className={`${main.p} pAr`}>{t.our_value.employeeLoyalty.desc}</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.teamWork.title}</h6>
                <p className={`${main.p} pAr`}>{t.our_value.teamWork.desc}</p>
              </div>
              <div className='col-xs-12 col-sm-6 col-md-4 col-lg-4'>
                <h6>{t.our_value.perseverance.title}</h6>
                <p className={`${main.p} pAr`}>{t.our_value.perseverance.desc}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Our Services */}
      <Services id='our_services' />

      {/* Free services */}
      <div className={`row ${main.banner} ${main.free_service}`} id='why_us'>
        <div className={main.img}>
          <div className={main.cover}>
            <div className='container'>
              <div className={`row`}>
                <h4>{t.free_services.title}</h4>
                <p>{t.free_services.desc}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Testimonials */}
      <div className={`row ${main.testemonials}`} id='testimonials'>
        <div class='container'>
          <h4>{t.testemonials.title}</h4>
          <Slider {...settings}>
            <div style={{ 'margin-bottom': '15px', 'padding': '0 10px' }}>
              <div className={`card ${main.card}`}>
                <h5>{t.testemonials.a.name}</h5>
                <p>{t.testemonials.a.title}</p>
                <small>{t.testemonials.a.desc}</small>
              </div>
            </div>
            <div style={{ 'margin-bottom': '15px', 'padding': '0 10px' }}>
              <div className={`card ${main.card}`}>
                <h5>{t.testemonials.a.name}</h5>
                <p>{t.testemonials.a.title}</p>
                <small>{t.testemonials.a.desc}</small>
              </div>
            </div>
            <div style={{ 'margin-bottom': '15px', 'padding': '0 10px' }}>
              <div className={`card ${main.card}`}>
                <h5>{t.testemonials.c.name}</h5>
                <p>{t.testemonials.c.title}</p>
                <small>{t.testemonials.c.desc}</small>
              </div>
            </div>
            <div style={{ 'margin-bottom': '15px', 'padding': '0 10px' }}>
              <div className={`card ${main.card}`}>
                <h5>{t.testemonials.c.name}</h5>
                <p>{t.testemonials.c.title}</p>
                <small>{t.testemonials.c.desc}</small>
              </div>
            </div>


          </Slider>
        </div>
      </div>

      {/* Team members */}
      <div className={`row ${main.members}`} id='our_team'>
        <div className='container'>
          <h4>{t.teamWork.title}</h4>
          <div className={`row`}>
            {/* row 1 === 1 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'center' }}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url(${ibrahim_alsulmi.src})` }}></div>
                <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.ibrahim_alsulmi.name}</h5>
                  <p>{t.teamWork.ibrahim_alsulmi.title}</p>
                </div>
              </div>
            </div>

            {/* row 2 === 1 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'center' }}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url(${khaled.src})` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.khaled_salah.name}</h5>
                  <p>{t.teamWork.khaled_salah.title}</p>
                </div>
              </div>
            </div>

            {/* row 3 === 2 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'right'}}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url(${otba_bakr.src})` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.otba_bakr.name}</h5>
                  <p>{t.teamWork.otba_bakr.title}</p>
                </div>
              </div>

              <div style={{ 'text-align': 'left'}}>
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.maha_alqasem.name}</h5>
                  <p>{t.teamWork.maha_alqasem.title}</p>
                  </div>
                </div>
              </div>
            </div>
            {/* row 4 === 3 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'right'}}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.ahmed_yahia.name}</h5>
                  <p>{t.teamWork.ahmed_yahia.title}</p>
                </div>
              </div>

              <div style={{ 'text-align': 'center'}} >
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.abelmaged_sharaqi.name}</h5>
                  <p>{t.teamWork.abelmaged_sharaqi.title}</p>
                  </div>
                </div>
              </div>
              <div style={{ 'text-align': 'left'}}>
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.mona_sultan.name}</h5>
                  <p>{t.teamWork.mona_sultan.title}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* row 5 === 3 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'right'}}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url(${yosef_alsulmi.src})` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.yosef_alsulmi.name}</h5>
                  <p>{t.teamWork.yosef_alsulmi.title}</p>
                </div>
              </div>

              <div style={{ 'text-align': 'center'}}>
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.tasneem_mohamed.name}</h5>
                  <p>{t.teamWork.tasneem_mohamed.title}</p>
                  </div>
                </div>
              </div>
              <div style={{ 'text-align': 'left'}}>
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.moaz_alsulmi.name}</h5>
                  <p>{t.teamWork.moaz_alsulmi.title}</p>
                  </div>
                </div>
              </div>
            </div>
            {/* row 6 === 2 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'right'}}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.shaden_alsulmi.name}</h5>
                  <p>{t.teamWork.shaden_alsulmi.title}</p>
                </div>
              </div>

              <div style={{ 'text-align': 'left'}}>
                <div className={`card ${main.card}`}>
                  <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                  <div className={`row ${main.employee}`}>
                  <h5>{t.teamWork.mohamed_ghareeb.name}</h5>
                  <p>{t.teamWork.mohamed_ghareeb.title}</p>
                  </div>
                </div>
              </div>
            </div>
            {/* row 7 === 1 */}
            <div className={`row ${main.FCard}`} style={{ 'text-align': 'center'}}>
              <div className={`card ${main.card}`}>
                <div className={`${main.team_imgs}`} style={{ 'background-image': `url('https://placeholder.photo/img/220')` }}></div>
                <div className={`row ${main.employee}`}>
                <h5>{t.teamWork.mohamed_alramady.name}</h5>
                  <p>{t.teamWork.mohamed_alramady.title}</p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Parteners */}
      <div class="row">
        <div className={main.whattheysay} id='parteners'>
          <div class="row" id="portfolio">
            <h4>{t.parteners}</h4>
          </div>

          <div class="row">
            <div className={`${main.slider}`}>
              <div class={main.slide_track}>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={dell.src} />
                    </div>
                  </div>
                </div>

                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={aldawaa.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={aldawaa_pharmacy.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={asalet.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={atlas.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={browneagle.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={fullscreen.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={moj.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={secureEyes.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={servicesSolutions.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={sharek.src} />
                    </div>
                  </div>
                </div>
                <div className={main.slide}>
                  <div className={main.card + ' ' + main.review}>
                    <div>
                      <div className={main.proj1 + ' ' + main.revImg + ' ' + main.r1}></div>
                      {/* <Image className="card-img-top" src={aboutImg} alt="Card image cap" /> */}
                    </div>
                    <div className="card-body">
                      <img src={spsc.src} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    </>
  )
}
